### PR TITLE
Convert use of onKeyDown to onKeyPress

### PR DESCRIPTION
**Pull request by tmns**
Hi Karl,

No problem on the late reply - as you can see I also don't reply so promptly ^_^

I carved some time out though to complete this, which resolves issue #11 

If there are any q's or problems feel free to reach out!

### CODE REVIEW

**Comment by karlhadwen** [comment]
This is seriously awesome, thank you for your work! I'm going to take some time tomorrow to take a look at this, thanks again!

**Comment by karlhadwen** [comment]
Hey dude, sorry for the late reply, totally forgot to look at this! I've just ran it locally and I've a few failing tests, is this the same happening for you? I tested master and the tests seem fine.

**Comment by tmns** [comment]
Hmm, are the tests failing due to either `firebase.js` not being present or not having valid values in its config? As long as I have a valid firebase config all tests pass on my end.

**Comment by karlhadwen** [comment]
Ah, my apologies, I did replace the `firebase.js` file but VSCode was caching the old one. I can now see the tests are working fine. The only issue I see with using if statements here is that there's no fallback if the condition is met, e.g. lowering coverage on the branch--taking it from 100% to 81.82.

Screenshot 2020-01-20 at 11 23 56 pm

**Comment by tmns** [comment]
Hmm I see.. I'm not really sure what the fallback could be in this case though.. Either the key that was pressed was the `Enter` key, which means we should perform whatever action correlates to a click (e.g. in `AddProject` this means call `addProject()`) or the key that was pressed was any other key, in which case we don't want to do anything. So how do we add a fallback for `do nothing`?

I also don't really understand why it states that (again e.g. for `AddProject`) that line 47, 62, etc. are uncovered. In `AddProject.spec.js` I currently have the test:

```javascript
    it('renders <AddProject /> and adds a project using onKeyPress', () => {
      const { queryByTestId } = render(<AddProject shouldShow />);
      expect(queryByTestId('add-project')).toBeTruthy();

      fireEvent.change(queryByTestId('project-name'), {
        target: { value: 'Best project in the world!' },
      });
      expect(queryByTestId('project-name').value).toBe(
        'Best project in the world!'
      );
      fireEvent.keyPress(queryByTestId('add-project-submit'), {
        key: 'Enter',
        charCode: 13
      });
      expect(queryByTestId('add-project')).toBeTruthy();
      expect(queryByTestId('add-project-inner')).toBeFalsy();
});
```
Isn't that testing line 47 adequately? I even added another `it` after that tests for the case of the user pressing `Tab` instead of `Enter` - in which case we would expect `expect(queryByTestId('add-project-inner')).toBeTruthy();` but it still said line 47 was uncovered.

Maybe you can shed a little light on this when you have a moment? Thanks for your time and help!

**Comment by LucasShaffer** [comment]
I agree with tmns that the conditional should be there to look for the 'Enter' press and not just any key press. It is what I ended up doing in mine. @tmns the reason that there is less coverage and that @karlhadwen is worried about the branch coverage lowering is because a non 'Enter' press is not tested. Adding something like the following should suffice:

``` JavaScript
it('renders <AddProject /> and adds a project using onKeyPress', () => {
  const { queryByTestId } = render(<AddProject shouldShow />);
  expect(queryByTestId('add-project')).toBeTruthy();

  fireEvent.change(queryByTestId('project-name'), {
    target: { value: 'Best project in the world!' },
  });
  expect(queryByTestId('project-name').value).toBe(
    'Best project in the world!'
  );

// START OF THE ADDED CODE
  fireEvent.keyPress(queryByTestId('add-project-submit'), {
    key: 'a',
    charCode: 'a'
  });
  expect(queryByTestId('add-project')).toBeFalsy();
//END OF THE ADDED CODE

  fireEvent.keyPress(queryByTestId('add-project-submit'), {
    key: 'Enter',
    charCode: 13
  });
  expect(queryByTestId('add-project')).toBeTruthy();
  expect(queryByTestId('add-project-inner')).toBeFalsy();
});
```
I can create another PR if needed. This should be added to all locations where there is the conditional that is looking for the 'Enter' key press. Then the branches % and untested lines should be resolved.

**Comment by tmns** [comment]
Hi @LucasShaffer! Thanks for the message / help. Sure, go ahead and make another PR if you feel up to it - as it's been quite a while since I've looked at this and don't really have a whole lot of capacity at the moment! I'll go ahead and close this one.

**Pull request closed without merging**
